# Generated by Django 4.1.6 on 2023-02-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
